# Generated by Django 5.1.7 on 2025-04-26 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0030_userprofile_max_notes_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateTimeField(help_text='客戶期望的預約開始時間', verbose_name='預約日期與時間')),
                ('status', models.CharField(choices=[('requested', '客戶請求'), ('pending_confirmation', '待店家確認'), ('confirmed', '已確認'), ('cancelled_customer', '客戶取消'), ('cancelled_salon', '店家/美容師取消'), ('no_show_customer', '客戶未到'), ('completed', '已完成')], db_index=True, default='requested', help_text='追蹤預約的目前進度', max_length=30, verbose_name='預約狀態')),
                ('status_updated_at', models.DateTimeField(auto_now=True, help_text='此狀態最後一次被更新的時間', verbose_name='狀態最後更新時間')),
                ('customer_notes', models.TextField(blank=True, help_text='記錄客戶透過LINE提出的原始需求或特殊要求', verbose_name='客戶備註 (來自LINE)')),
                ('admin_notes', models.TextField(blank=True, help_text='管理員內部溝通或記錄，例如確認過程、特殊情況等', verbose_name='內部備註 (管理員用)')),
                ('confirmation_notes', models.TextField(blank=True, help_text='記錄與店家確認的結果，或回報給客戶的訊息摘要', verbose_name='確認/回報備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記錄建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='記錄最後更新時間')),
                ('beautician', models.ForeignKey(help_text='選擇被預約的美容師', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='myapp.animal', verbose_name='美容師')),
                ('created_by', models.ForeignKey(blank=True, help_text='登打此筆預約記錄的管理員帳號', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='記錄建立者')),
                ('customer', models.ForeignKey(help_text='選擇進行預約的客戶帳號', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='客戶/會員')),
            ],
            options={
                'verbose_name': '預約記錄',
                'verbose_name_plural': '預約記錄',
                'ordering': ['-appointment_datetime'],
                'indexes': [models.Index(fields=['appointment_datetime', 'status'], name='appointment_appoint_825195_idx')],
            },
        ),
    ]
