# Generated by Django 5.1.7 on 2025-04-26 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('myapp', '0030_userprofile_max_notes_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_datetime'], 'verbose_name': '預約/服務記錄', 'verbose_name_plural': '預約/服務記錄'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_walk_in',
            field=models.BooleanField(db_index=True, default=False, help_text='勾選此項表示此記錄為客人現場指定(順上)，而非提前預約。', verbose_name='是否為順上/現場'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.DateTimeField(help_text='預約開始時間 或 順上服務實際開始時間', verbose_name='預約/服務時間'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='beautician',
            field=models.ForeignKey(help_text='選擇提供服務的美容師', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='myapp.animal', verbose_name='美容師'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='登打此筆記錄的管理員帳號', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='記錄建立者'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(help_text='選擇進行預約或服務的客戶帳號', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='客戶/會員'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='記錄客戶提出的原始需求或特殊要求', verbose_name='客戶備註 (來自LINE/現場)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('requested', '客戶請求'), ('pending_confirmation', '待店家確認'), ('confirmed', '已確認/進行中'), ('cancelled_customer', '客戶取消'), ('cancelled_salon', '店家/美容師取消'), ('no_show_customer', '客戶未到'), ('completed', '已完成')], db_index=True, default='requested', help_text='追蹤記錄的目前進度', max_length=30, verbose_name='記錄狀態'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['is_walk_in', 'status'], name='appointment_is_walk_c21aac_idx'),
        ),
    ]
