# Generated by Django 5.1.7 on 2025-04-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_appointment_is_walk_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.DateTimeField(help_text='預約開始時間 或 現場服務實際發生時間', verbose_name='預約/服務時間'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_walk_in',
            field=models.BooleanField(db_index=True, default=False, help_text='勾選此項表示此記錄為客人現場指定或看台，而非提前預約。', verbose_name='是否為現場單'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('requested', '客預約'), ('pending_confirmation', '待店家確認'), ('confirmed_waiting', '客待到店'), ('checked_in', '客已到'), ('rejected_by_customer', '客看台未上'), ('completed', '客結束'), ('cancelled_customer', '客取消'), ('cancelled_salon', '店家/美容師取消'), ('no_show_customer', '客未到')], db_index=True, default='requested', help_text='追蹤記錄的目前進度', max_length=30, verbose_name='記錄狀態'),
        ),
    ]
