# Generated by Django 5.1.7 on 2025-04-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_appointment_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('requested', '客詢問預約'), ('pending_confirmation', '待店家確認'), ('confirmed_waiting', '預約完成待進店'), ('checked_in', '客已到店'), ('completed', '客結束'), ('rejected_by_customer', '客看台未上'), ('cancelled_customer', '客取消'), ('no_reply_customer', '客未回覆'), ('cancelled_salon', '店家/美容師取消'), ('no_show_customer', '客未到')], db_index=True, default='requested', help_text='追蹤記錄的目前進度', max_length=30, verbose_name='記錄狀態'),
        ),
    ]
