# Generated by Django 5.1.7 on 2025-04-26 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_status'),
        ('myapp', '0030_userprofile_max_notes_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_datetime'], 'verbose_name': '預約/現場記錄', 'verbose_name_plural': '預約/現場記錄'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='管理員內部溝通或記錄', verbose_name='內部備註 (管理員用)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.DateTimeField(help_text='預約開始時間 或 現場服務/看台實際發生時間', verbose_name='預約/服務時間'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='beautician',
            field=models.ForeignKey(blank=True, help_text='選擇提供服務的美容師。若是『預約看現場』或『現場看台』，請將此欄留空。', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.animal', verbose_name='美容師'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='confirmation_notes',
            field=models.TextField(blank=True, help_text='記錄與店家確認的結果或回報訊息', verbose_name='確認/回報備註'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_walk_in',
            field=models.BooleanField(db_index=True, default=False, help_text='勾選此項表示此記錄為客人『預約看現場』或『現場順上/看台』，而非提前預約特定美容師。', verbose_name='是否為現場相關'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['beautician', 'status'], name='appointment_beautic_3c559b_idx'),
        ),
    ]
