# Generated by Django 5.1.7 on 2025-04-26 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_options_and_more'),
        ('myapp', '0030_userprofile_max_notes_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='beautician',
            field=models.ForeignKey(blank=True, help_text='選擇提供服務的美容師。若是『現場看台』，請將此欄留空。', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.animal', verbose_name='美容師'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_walk_in',
            field=models.BooleanField(db_index=True, default=False, help_text='勾選此項表示此記錄為客人『現場看台』或『現場順上』，而非提前預約特定美容師。', verbose_name='現場看台'),
        ),
    ]
