# Generated by Django 5.1.7 on 2025-04-17 02:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0022_animal_aliases_animal_created_at_animal_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slots', models.CharField(blank=True, help_text='例如 "14.15.16", "預約滿", "人到再約"', max_length=300, null=True, verbose_name='今日時段')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新時間')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules_records', to='myapp.animal', verbose_name='美容師')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules_records', to='myapp.hall', verbose_name='館別')),
            ],
            options={
                'verbose_name': '今日班表記錄',
                'verbose_name_plural': '今日班表記錄',
                'ordering': ['hall__order', 'animal__order', 'animal__name'],
                'indexes': [models.Index(fields=['hall'], name='schedule_pa_hall_id_23cb93_idx'), models.Index(fields=['animal'], name='schedule_pa_animal__12b303_idx')],
                'unique_together': {('hall', 'animal')},
            },
        ),
    ]
