# Generated by Django 5.1.7 on 2025-03-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_exclusive',
            field=models.BooleanField(default=False, verbose_name='獨家'),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='熱門'),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_newcomer',
            field=models.BooleanField(default=False, verbose_name='新人'),
        ),
    ]
