# Generated by Django 5.1.7 on 2025-03-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_animal_is_exclusive_animal_is_hot_animal_is_newcomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='介紹'),
        ),
    ]
