# Generated by Django 5.1.7 on 2025-03-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_review_approved_alter_review_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年紀'),
        ),
        migrations.AddField(
            model_name='review',
            name='cup',
            field=models.CharField(blank=True, choices=[('天然', '天然'), ('醫美', '醫美'), ('自體醫美', '自體醫美'), ('不確定', '不確定')], max_length=20, null=True, verbose_name='罩杯'),
        ),
        migrations.AddField(
            model_name='review',
            name='face',
            field=models.CharField(blank=True, choices=[('醫美', '醫美'), ('可愛', '可愛'), ('甜美', '甜美'), ('稚嫩', '稚嫩'), ('呆萌', '呆萌'), ('清秀', '清秀'), ('仙氣', '仙氣'), ('艷麗', '艷麗'), ('性感', '性感'), ('古典', '古典'), ('個性', '個性'), ('鄰家', '鄰家'), ('大眾', '大眾'), ('平凡', '平凡'), ('單眼皮', '單眼皮'), ('輕熟', '輕熟'), ('熟女', '熟女')], max_length=20, null=True, verbose_name='臉蛋'),
        ),
        migrations.AddField(
            model_name='review',
            name='looks',
            field=models.CharField(blank=True, choices=[('S', 'S級 (一見難忘)'), ('A', 'A級 (出眾)'), ('B', 'B級 (優異)'), ('C', 'C級 (中上)'), ('D', 'D級 (大眾)'), ('E', 'E級 (較平凡)')], max_length=1, null=True, verbose_name='顏值'),
        ),
        migrations.AddField(
            model_name='review',
            name='music',
            field=models.CharField(blank=True, choices=[('未詢問', '未詢問'), ('無此服務', '無此服務'), ('可加值', '可加值 (費用待填)'), ('自談', '可加值 (自談)')], max_length=20, null=True, verbose_name='音樂'),
        ),
        migrations.AddField(
            model_name='review',
            name='physique',
            field=models.CharField(blank=True, choices=[('骨感', '骨感'), ('瘦', '瘦'), ('瘦有肉', '瘦有肉'), ('標準', '標準'), ('曲線迷人', '曲線迷人'), ('瘦偏肉', '瘦偏肉'), ('微肉', '微肉'), ('棉花糖', '棉花糖')], max_length=20, null=True, verbose_name='體態'),
        ),
        migrations.AddField(
            model_name='review',
            name='scale',
            field=models.CharField(blank=True, choices=[('三光', '三光'), ('兩光', '兩光'), ('LG', 'LG'), ('親', '親'), ('舔', '舔'), ('伸', '伸'), ('摸', '摸'), ('磨', '磨')], max_length=20, null=True, verbose_name='尺度'),
        ),
        migrations.AddField(
            model_name='review',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('白皙', '白皙'), ('偏白', '偏白'), ('正常黃', '正常黃'), ('偏黃', '偏黃'), ('健康黑', '健康黑')], max_length=20, null=True, verbose_name='膚色'),
        ),
        migrations.AddField(
            model_name='review',
            name='skin_texture',
            field=models.CharField(blank=True, choices=[('絲滑', '絲滑'), ('還不錯', '還不錯'), ('正常', '正常'), ('普通', '普通')], max_length=20, null=True, verbose_name='膚質'),
        ),
        migrations.AddField(
            model_name='review',
            name='sports',
            field=models.CharField(blank=True, choices=[('未詢問', '未詢問'), ('無此服務', '無此服務'), ('可加值', '可加值 (費用待填)'), ('自談', '可加值 (自談)'), ('體含音', '體含音')], max_length=20, null=True, verbose_name='體育'),
        ),
        migrations.AddField(
            model_name='review',
            name='temperament',
            field=models.CharField(blank=True, choices=[('優雅', '優雅'), ('成熟', '成熟'), ('清新', '清新'), ('自然', '自然'), ('禮貌', '禮貌'), ('女友感', '女友感'), ('女人味', '女人味'), ('OL', 'OL'), ('台妹', '台妹'), ('普通', '普通')], max_length=20, null=True, verbose_name='氣質'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='心得'),
        ),
    ]
