# Generated by Django 5.1.7 on 2025-03-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_review_age_review_cup_review_face_review_looks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='looks',
            field=models.CharField(blank=True, choices=[('S級 (一見難忘)', 'S級 (一見難忘)'), ('A級 (出眾', 'A級 (出眾)'), ('B級 (優異)', 'B級 (優異)'), ('C級 (中上)', 'C級 (中上)'), ('D級 (大眾)', 'D級 (大眾)'), ('E級 (較平凡)', 'E級 (較平凡)')], max_length=20, null=True, verbose_name='顏值'),
        ),
    ]
