# Generated by Django 5.1.7 on 2025-03-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_review_looks'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cup_size',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='罩杯大小'),
        ),
        migrations.AddField(
            model_name='review',
            name='music_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='音樂價格'),
        ),
        migrations.AddField(
            model_name='review',
            name='sports_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='體育價格'),
        ),
        migrations.AlterField(
            model_name='review',
            name='face',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='臉蛋'),
        ),
        migrations.AlterField(
            model_name='review',
            name='looks',
            field=models.CharField(blank=True, choices=[('S級 (一見難忘)', 'S級 (一見難忘)'), ('A級 (出眾)', 'A級 (出眾)'), ('B級 (優異)', 'B級 (優異)'), ('C級 (中上)', 'C級 (中上)'), ('D級 (大眾)', 'D級 (大眾)'), ('E級 (較平凡)', 'E級 (較平凡)')], max_length=20, null=True, verbose_name='顏值'),
        ),
        migrations.AlterField(
            model_name='review',
            name='scale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='尺度'),
        ),
        migrations.AlterField(
            model_name='review',
            name='temperament',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='氣質'),
        ),
    ]
