# Generated by Django 5.1.7 on 2025-04-10 07:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='標題')),
                ('content', models.TextField(verbose_name='公告內容')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='啟用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['hall__order', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='pendingappointment',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='animal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='啟用中'),
        ),
        migrations.AddField(
            model_name='animal',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='hall',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='myapp.hall', verbose_name='館別'),
        ),
        migrations.AlterField(
            model_name='note',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='myapp.animal'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='筆記內容'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingappointment',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_users', to='myapp.animal'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='review',
            name='cup',
            field=models.CharField(blank=True, choices=[('天然', '天然'), ('醫美', '醫美'), ('自體醫美', '自體醫美'), ('不確定', '不確定')], max_length=20, null=True, verbose_name='罩杯類型'),
        ),
        migrations.AlterField(
            model_name='review',
            name='cup_size',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='罩杯大小'),
        ),
        migrations.AlterField(
            model_name='review',
            name='music_price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='音樂價格'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sports_price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='體育價格'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('user', 'animal')},
        ),
        migrations.AlterUniqueTogether(
            name='pendingappointment',
            unique_together={('user', 'animal')},
        ),
    ]
