# Generated by Django 5.1.7 on 2025-04-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_animal_is_hidden_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='推薦'),
        ),
    ]
