# Generated by Django 5.1.7 on 2025-04-14 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_animal_is_recommended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年紀')),
                ('looks', models.CharField(blank=True, choices=[('S級 (一見難忘)', 'S級 (一見難忘)'), ('A級 (出眾)', 'A級 (出眾)'), ('B級 (優異)', 'B級 (優異)'), ('C級 (中上)', 'C級 (中上)'), ('D級 (大眾)', 'D級 (大眾)'), ('E級 (較平凡)', 'E級 (較平凡)')], max_length=20, null=True, verbose_name='顏值')),
                ('face', models.CharField(blank=True, max_length=100, null=True, verbose_name='臉蛋')),
                ('temperament', models.CharField(blank=True, max_length=100, null=True, verbose_name='氣質')),
                ('physique', models.CharField(blank=True, choices=[('骨感', '骨感'), ('瘦', '瘦'), ('瘦有肉', '瘦有肉'), ('標準', '標準'), ('曲線迷人', '曲線迷人'), ('瘦偏肉', '瘦偏肉'), ('微肉', '微肉'), ('棉花糖', '棉花糖')], max_length=20, null=True, verbose_name='體態')),
                ('cup', models.CharField(blank=True, choices=[('天然', '天然'), ('醫美', '醫美'), ('自體醫美', '自體醫美'), ('不確定', '不確定')], max_length=20, null=True, verbose_name='罩杯類型')),
                ('cup_size', models.CharField(blank=True, max_length=5, null=True, verbose_name='罩杯大小')),
                ('skin_texture', models.CharField(blank=True, choices=[('絲滑', '絲滑'), ('還不錯', '還不錯'), ('正常', '正常'), ('普通', '普通')], max_length=20, null=True, verbose_name='膚質')),
                ('skin_color', models.CharField(blank=True, choices=[('白皙', '白皙'), ('偏白', '偏白'), ('正常黃', '正常黃'), ('偏黃', '偏黃'), ('健康黑', '健康黑')], max_length=20, null=True, verbose_name='膚色')),
                ('music', models.CharField(blank=True, choices=[('未詢問', '未詢問'), ('無此服務', '無此服務'), ('可加值', '可加值 (費用待填)'), ('自談', '可加值 (自談)')], max_length=20, null=True, verbose_name='音樂')),
                ('music_price', models.CharField(blank=True, max_length=20, null=True, verbose_name='音樂價格')),
                ('sports', models.CharField(blank=True, choices=[('未詢問', '未詢問'), ('無此服務', '無此服務'), ('可加值', '可加值 (費用待填)'), ('自談', '可加值 (自談)'), ('體含音', '體含音')], max_length=20, null=True, verbose_name='體育')),
                ('sports_price', models.CharField(blank=True, max_length=20, null=True, verbose_name='體育價格')),
                ('scale', models.CharField(blank=True, max_length=100, null=True, verbose_name='尺度')),
                ('content', models.TextField(blank=True, null=True, verbose_name='心得內容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交時間')),
                ('approved', models.BooleanField(db_index=True, default=False, verbose_name='已審核')),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='審核時間')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='過期時間')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_reviews', to='myapp.animal', verbose_name='動物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_reviews', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '限時動態心得',
                'verbose_name_plural': '限時動態心得',
                'ordering': ['-approved_at', '-created_at'],
            },
        ),
    ]
