# Generated by Django 5.1.7 on 2025-04-14 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_storyreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_image', models.ImageField(help_text='請上傳 A4 尺寸的圖片', upload_to='weekly_schedules/', verbose_name='班表圖片')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('hall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule', to='myapp.hall', verbose_name='館別')),
            ],
            options={
                'verbose_name': '每週班表',
                'verbose_name_plural': '每週班表',
                'ordering': ['hall__order', 'hall__name'],
            },
        ),
    ]
