# Generated by Django 5.1.7 on 2025-04-14 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_weeklyschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyschedule',
            options={'ordering': ['hall__order', 'hall__name', 'order'], 'verbose_name': '每週班表圖片', 'verbose_name_plural': '每週班表圖片'},
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='用於排序同一個館別的多張班表圖片，數字越小越前面', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='myapp.hall', verbose_name='館別'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='schedule_image',
            field=models.ImageField(help_text='請上傳班表圖片', upload_to='weekly_schedules/', verbose_name='班表圖片'),
        ),
    ]
