# Generated by Django 5.1.7 on 2025-04-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_weeklyschedule_options_weeklyschedule_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['-is_active', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='hall',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='啟用中'),
        ),
    ]
