# Generated by Django 5.1.7 on 2025-04-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_hall_options_hall_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['-status', 'order', 'name']},
        ),
        migrations.RemoveField(
            model_name='hall',
            name='is_active',
        ),
        migrations.AddField(
            model_name='hall',
            name='status',
            field=models.IntegerField(choices=[(0, '停用'), (1, '啟用'), (2, '隱藏')], db_index=True, default=1, help_text='啟用:正常顯示; 隱藏:選單不顯示但相關資料保留; 停用:完全不顯示', verbose_name='狀態'),
        ),
    ]
