# Generated by Django 5.1.7 on 2025-04-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_hall_options_remove_hall_is_active_hall_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['hall__order', 'hall__name', 'order', 'name'], 'verbose_name': '美容師', 'verbose_name_plural': '美容師管理'},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': '公告', 'verbose_name_plural': '公告管理'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['-is_active', 'order', 'name'], 'verbose_name': '館別', 'verbose_name_plural': '館別管理'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-updated_at'], 'verbose_name': '用戶筆記', 'verbose_name_plural': '用戶筆記管理'},
        ),
        migrations.AlterModelOptions(
            name='pendingappointment',
            options={'ordering': ['-added_at'], 'verbose_name': '待約項目', 'verbose_name_plural': '待約清單管理'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': '一般心得', 'verbose_name_plural': '一般心得管理'},
        ),
        migrations.AlterModelOptions(
            name='storyreview',
            options={'ordering': ['-approved_at', '-created_at'], 'verbose_name': '限時動態心得', 'verbose_name_plural': '限時動態心得管理'},
        ),
        migrations.AlterModelOptions(
            name='weeklyschedule',
            options={'ordering': ['hall__order', 'hall__name', 'order'], 'verbose_name': '每週班表圖片', 'verbose_name_plural': '每週班表圖片管理'},
        ),
        migrations.RemoveField(
            model_name='hall',
            name='status',
        ),
        migrations.AddField(
            model_name='hall',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='勾選表示館別正常營運並顯示於前台，取消勾選則隱藏（例如裝修或暫停營業）。', verbose_name='啟用中'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_active',
            field=models.BooleanField(default=True, help_text='美容師本身是否啟用', verbose_name='啟用中'),
        ),
    ]
