# Generated by Django 5.1.7 on 2025-04-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_animal_options_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['hall__order', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['-is_active', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='pendingappointment',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storyreview',
            options={'ordering': ['-approved_at', '-created_at'], 'verbose_name': '限時動態心得', 'verbose_name_plural': '限時動態心得'},
        ),
        migrations.AlterModelOptions(
            name='weeklyschedule',
            options={'ordering': ['hall__order', 'hall__name', 'order'], 'verbose_name': '每週班表圖片', 'verbose_name_plural': '每週班表圖片'},
        ),
        migrations.AddField(
            model_name='hall',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True, help_text='勾選此項，該館別按鈕才會顯示在前端頁面。取消勾選可隱藏按鈕，但不影響後台操作或資料關聯。', verbose_name='前端顯示'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='啟用中'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='啟用中'),
        ),
    ]
