# Generated by Django 5.1.7 on 2025-04-17 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_animal_options_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='aliases',
            field=models.JSONField(blank=True, default=list, help_text='儲存可能的暱稱或舊名列表 (例如 ["小花", "小花@A店"])', verbose_name='別名/曾用名'),
        ),
        migrations.AddField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='建立時間'),
        ),
        migrations.AddField(
            model_name='animal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='cup_size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='罩杯'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='myapp.hall', verbose_name='目前館別'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='啟用中'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='order',
            field=models.PositiveIntegerField(default=999, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='time_slot',
            field=models.CharField(blank=True, help_text='此欄位不再用於顯示每日班表，僅供參考。', max_length=200, verbose_name='預設時段(舊)'),
        ),
    ]
