# Generated by Django 5.1.7 on 2025-04-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_animal_aliases_animal_created_at_animal_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['-is_active', 'order', 'name'], 'verbose_name': '館別', 'verbose_name_plural': '館別'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-updated_at'], 'verbose_name': '用戶筆記', 'verbose_name_plural': '用戶筆記'},
        ),
        migrations.AlterModelOptions(
            name='pendingappointment',
            options={'ordering': ['-added_at'], 'verbose_name': '待約項目', 'verbose_name_plural': '待約項目'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': '心得評論', 'verbose_name_plural': '心得評論'},
        ),
        migrations.AddField(
            model_name='hall',
            name='schedule_format_type',
            field=models.CharField(choices=[('format_a', '格式A (舊LINE格式)'), ('chatanghui', '茶湯會格式')], default='format_a', help_text='指定此館別使用的班表文字格式，以便系統選擇正確的解析器', max_length=20, verbose_name='班表格式類型'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='數字越小越前面', verbose_name='排序'),
        ),
    ]
