# Generated by Django 5.1.7 on 2025-04-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_hall_schedule_format_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTitleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(help_text='例如：新手上路、評論達人', max_length=50, unique=True, verbose_name='稱號名稱')),
                ('min_review_count', models.PositiveIntegerField(help_text='使用者累積的已審核心得總數達到此數量(包含)即可獲得此稱號', unique=True, verbose_name='最低心得數')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='取消勾選可暫時停用此稱號規則，而不需刪除。', verbose_name='啟用中')),
            ],
            options={
                'verbose_name': '使用者稱號規則',
                'verbose_name_plural': '使用者稱號規則',
                'ordering': ['-min_review_count'],
            },
        ),
        migrations.AlterField(
            model_name='hall',
            name='schedule_format_type',
            field=models.CharField(choices=[('format_a', '格式A (舊LINE格式)'), ('chatanghui', '茶湯會格式'), ('xinyuan', '芯苑格式'), ('shouzhongqing', '手中情格式'), ('pokemon', '寶可夢格式'), ('aibao', '愛寶格式'), ('hanxiang', '含香格式'), ('pandora', '潘朵拉格式'), ('wangfei', '王妃格式'), ('lezuan', '樂鑽格式')], default='format_a', help_text='指定此館別使用的班表文字格式，以便系統選擇正確的解析器', max_length=20, verbose_name='班表格式類型'),
        ),
    ]
