# Generated by Django 5.1.7 on 2025-04-20 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_usertitlerule_alter_hall_schedule_format_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('good_to_have_you', '有你真好'), ('good_looking', '人帥真好')], db_index=True, max_length=20, verbose_name='回饋類型')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='回饋時間')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='myapp.review', verbose_name='一般心得')),
                ('story_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='myapp.storyreview', verbose_name='限時動態心得')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to=settings.AUTH_USER_MODEL, verbose_name='回饋者')),
            ],
            options={
                'verbose_name': '心得回饋記錄',
                'verbose_name_plural': '心得回饋記錄',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['review', 'feedback_type'], name='myapp_revie_review__89409e_idx'), models.Index(fields=['story_review', 'feedback_type'], name='myapp_revie_story_r_5465c8_idx')],
                'unique_together': {('user', 'review', 'feedback_type'), ('user', 'story_review', 'feedback_type')},
            },
        ),
    ]
