# Generated by Django 5.1.7 on 2025-04-20 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_reviewfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reward_granted',
            field=models.BooleanField(default=False, help_text='標記此心得是否已觸發增加使用次數', verbose_name='已獎勵次數'),
        ),
        migrations.AddField(
            model_name='storyreview',
            name='reward_granted',
            field=models.BooleanField(default=False, help_text='標記此心得是否已觸發增加使用次數', verbose_name='已獎勵次數'),
        ),
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已審核'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_list_limit', models.PositiveIntegerField(default=10, verbose_name='待約清單剩餘次數')),
                ('notes_limit', models.PositiveIntegerField(default=10, verbose_name='我的筆記剩餘次數')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者檔案',
                'verbose_name_plural': '使用者檔案',
            },
        ),
    ]
