# Generated by Django 5.1.7 on 2025-04-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_review_reward_granted_storyreview_reward_granted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['hall__order', 'order', 'name'], 'verbose_name': '美容師', 'verbose_name_plural': '美容師'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-approved_at', '-created_at'], 'verbose_name': '心得評論', 'verbose_name_plural': '心得評論'},
        ),
        migrations.AddField(
            model_name='review',
            name='approved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='審核時間'),
        ),
        migrations.AlterField(
            model_name='storyreview',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_reviews', to='myapp.animal', verbose_name='美容師'),
        ),
    ]
