# Generated by Django 5.1.7 on 2025-04-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_animal_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, help_text='建議使用透明背景的 PNG 圖片，高度約 40-50px', null=True, upload_to='site_config/', verbose_name='網站 Logo (頁首左上角)')),
            ],
            options={
                'verbose_name': '網站設定',
                'verbose_name_plural': '網站設定',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='勾選此項，將此美容師顯示在首頁主打區塊（建議只勾選一位）', verbose_name='設為主打'),
        ),
    ]
