# Generated by Django 5.1.7 on 2025-04-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_siteconfiguration_animal_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_notes_limit',
            field=models.PositiveIntegerField(default=10, help_text='使用者當前可用的筆記總額度', verbose_name='我的筆記最大上限'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_pending_limit',
            field=models.PositiveIntegerField(default=10, help_text='使用者當前可用的待約總額度', verbose_name='待約清單最大上限'),
        ),
    ]
