# Generated by Django 5.1.7 on 2025-04-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_userprofile_max_notes_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='address',
            field=models.TextField(blank=True, help_text='輸入館別的完整地址，將用於複製訊息。', null=True, verbose_name='地址'),
        ),
    ]
