# Generated by Django 5.1.7 on 2025-05-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_hall_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='max_notes_limit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='max_pending_limit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notes_limit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pending_list_limit',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='desire_coins',
            field=models.PositiveIntegerField(default=10, help_text='用於執行特定操作的貨幣', verbose_name='慾望幣餘額'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reward_granted',
            field=models.BooleanField(default=False, help_text='標記此心得是否已觸發增加慾望幣', verbose_name='已獎勵'),
        ),
        migrations.AlterField(
            model_name='storyreview',
            name='reward_granted',
            field=models.BooleanField(default=False, help_text='標記此心得是否已觸發增加慾望幣', verbose_name='已獎勵'),
        ),
    ]
