# Generated by Django 5.1.7 on 2025-05-04 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_userprofile_max_notes_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreBookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='此美容師可被預約的特定日期', verbose_name='可約日期')),
                ('time_slots', models.CharField(blank=True, help_text='輸入此日期可預約的時段，例如 "14:00, 15:30, 17:00" 或 "下午班"', max_length=255, verbose_name='可約時段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_booking_slots', to='myapp.animal', verbose_name='美容師')),
            ],
            options={
                'verbose_name': '搶約專區時段',
                'verbose_name_plural': '搶約專區時段',
                'ordering': ['-date', 'animal__hall__order', 'animal__order', 'animal__name'],
                'unique_together': {('animal', 'date')},
            },
        ),
    ]
